dist: bionic
group: travis_latest
language: python
cache: ccache

os:
- linux
- osx
- windows

install:
- pip install meson==0.53.0 gcovr==4.2 ninja==1.8.2

script:
- mkdir build && cd build
- meson ..
- ninja
- ninja test
