name: Pull Actions

on: [pull_request, pull_request_review, pull_request_review_comment]

jobs:
  danger:
    name: Danger Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.6'
    - name: Setup environment
      run: |
        gem install bundler -v 2.1.4
        bundle install --jobs 4 --retry 3
    - name: Run Danger
      run: |
        export DANGER_GITHUB_API_TOKEN=${{ secrets.BOT_TOKEN }}
        bundle exec danger --verbose
